# Generated by Django 3.2.9 on 2021-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
